--  ******************************************************************************************
-- ***************  UPLOAD THE DATA IN AWS, THEN AFTER INTEGRATE IN SNOWFLAKE   ***********

--  ******************************************************************************************

-- CREATE S3 BUCKET > CREATE SUB FOLDER IN S3 BUCKET > CREATE POLICY WITH JSON COMMANDE > CREATE ROLE > EDIT TRUST RELATIONSHIP COMMANDE >
-- SET NOTIFICATION WITH SNOWFLAKE SNOWPIPE

CREATE OR REPLACE STORAGE INTEGRATION S3_INTE 
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::752432490499:role/czkbankanalysisrole' -- POLICY ARN
STORAGE_ALLOWED_LOCATIONS =('s3://czkbankanalysis/');  -- S3 BUCKET ARN

DESC INTEGRATION S3_INTE; -- STORAGE_AWS_IAM_USER_ARN COPY AND PAST IT IN ROLE TRUST RELATIONSHIP

CREATE OR REPLACE STAGE CZK_BANK_ST
URL ='s3://czkbankanalysis' --  S3 BUCKET ARN
file_format = CZK_BANK_ANALYSIS_CSV -- FILE FORMATE SNOWFLAKE
storage_integration = S3_INTE; -- STORAGE INTEGRATION NAME

LIST @CZK_BANK_ST;

SHOW STAGES;

--CREATE SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO EXISTING TABLE

--The AUTO_INGEST=true parameter specifies to read 
--- event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.

-- AFTER CREATIONG PIPE CONY NOTIFICATION IN SNOWFLAKE AND PAST IN S3 BUCKET NOTIFICATION PANAL

CREATE OR REPLACE PIPE BANK_SNOWPIPE_DISTRICT 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."DISTRICT" --yourdatabase -- your schema ---your table
FROM '@CZK_BANK_ST/district/' -- STAGE_NAME  s3_bucket_subfolde4r_name
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_ACCOUNT 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."ACCOUNT"
FROM '@CZK_BANK_ST/account/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_CARD 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."CARD"
FROM '@CZK_BANK_ST/Card/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_CLIENT 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."CLIENT"
FROM '@CZK_BANK_ST/client/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_DISP 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."DISPOSITION"
FROM '@CZK_BANK_ST/disposition/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_LOAN 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."LOAN"
FROM '@CZK_BANK_ST/loan/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_ORDER_TABLE 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."ORDER_TABLE"
FROM '@CZK_BANK_ST/order_table/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

CREATE OR REPLACE PIPE BANK_SNOWPIPE_TXNS 
AUTO_INGEST = TRUE AS
COPY INTO "CZK_BANK_ANALYSIS"."PUBLIC"."TRANSACTIONS"
FROM '@CZK_BANK_ST/transactions/'
FILE_FORMAT = CZK_BANK_ANALYSIS_CSV;

SHOW PIPES;

-- COMPLETE WHOLE PROCESS AND START UPLOAD DATA IN AWS AND RUN ALTER COMMANDE EACH TIME

--  *************************************************************************

SELECT count(*) FROM DISTRICT;
SELECT count(*) FROM ACCOUNT;
SELECT count(*) FROM TRANSACTIONS;
SELECT count(*) FROM DISPOSITION;
SELECT count(*) FROM CARD;
SELECT count(*) FROM ORDER_LIST;
SELECT count(*) FROM LOAN;
SELECT count(*) FROM CLIENT;

--  ******************************************************************

ALTER PIPE BANK_SNOWPIPE_DISTRICT refresh;
ALTER PIPE BANK_SNOWPIPE_ACCOUNT refresh;
ALTER PIPE BANK_SNOWPIPE_TXNS refresh;
ALTER PIPE BANK_SNOWPIPE_DISP refresh;
ALTER PIPE BANK_SNOWPIPE_CARD refresh;
ALTER PIPE BANK_SNOWPIPE_ORDER_LIST refresh;
ALTER PIPE BANK_SNOWPIPE_LOAN refresh;
ALTER PIPE BANK_SNOWPIPE_CLIENT refresh;

--  **********************************************************************

SELECT * FROM DISTRICT;
SELECT * FROM ACCOUNT;
SELECT * FROM TRANSACTIONS;
SELECT * FROM DISPOSITION;
SELECT * FROM CARD;
SELECT * FROM ORDER_LIST;
SELECT * FROM LOAN;
SELECT * FROM CLIENT;